import type { Icon } from '@phosphor-icons/react';
import {
  AirplaneInFlightIcon,
  BasketballIcon,
  BoatIcon,
  BookOpenIcon,
  BriefcaseIcon,
  BuildingsIcon,
  CalendarBlankIcon,
  CameraIcon,
  CarIcon,
  ClockIcon,
  CodeIcon,
  CoffeeIcon,
  ConfettiIcon,
  CpuIcon,
  DiceFiveIcon,
  FilmSlateIcon,
  FilmStripIcon,
  FireIcon,
  FlowerIcon,
  FootballIcon,
  ForkKnifeIcon,
  GameControllerIcon,
  GlobeIcon,
  GraduationCapIcon,
  GuitarIcon,
  HandHeartIcon,
  HeadphonesIcon,
  HeartIcon,
  ImageIcon,
  LightningIcon,
  MapPinIcon,
  MaskHappyIcon,
  MedalIcon,
  MegaphoneIcon,
  MicrophoneIcon,
  MicrophoneStageIcon,
  MoonIcon,
  MountainsIcon,
  MusicNoteIcon,
  MusicNotesIcon,
  PaintBrushIcon,
  PaletteIcon,
  PianoKeysIcon,
  QrCodeIcon,
  RadioIcon,
  RocketLaunchIcon,
  SealCheckIcon,
  ShieldCheckIcon,
  ShoppingBagIcon,
  SoccerBallIcon,
  SparkleIcon,
  SpeakerHighIcon,
  StarIcon,
  StorefrontIcon,
  SunIcon,
  TicketIcon,
  TrainIcon,
  TreeIcon,
  TreePalmIcon,
  TrophyIcon,
  UsersIcon,
  UsersThreeIcon,
  VideoCameraIcon,
  VolleyballIcon,
  WavesIcon,
  WineIcon,
  TennisBallIcon,
} from '@phosphor-icons/react';

export type PhosphorCategoryPicklistEntry = {
  /** Export name from `@phosphor-icons/react` (e.g. `MusicNotesIcon`) — store this in `icon_key`. */
  key: string;
  Icon: Icon;
};

/** Curated set aligned with event / venue / culture categories; matches main site package. */
export const CATEGORY_PHOSPHOR_ICONS: PhosphorCategoryPicklistEntry[] = [
  { key: 'MusicNotesIcon', Icon: MusicNotesIcon },
  { key: 'MusicNoteIcon', Icon: MusicNoteIcon },
  { key: 'PianoKeysIcon', Icon: PianoKeysIcon },
  { key: 'MicrophoneIcon', Icon: MicrophoneIcon },
  { key: 'MicrophoneStageIcon', Icon: MicrophoneStageIcon },
  { key: 'GuitarIcon', Icon: GuitarIcon },
  { key: 'HeadphonesIcon', Icon: HeadphonesIcon },
  { key: 'SpeakerHighIcon', Icon: SpeakerHighIcon },
  { key: 'RadioIcon', Icon: RadioIcon },
  { key: 'MegaphoneIcon', Icon: MegaphoneIcon },
  { key: 'BasketballIcon', Icon: BasketballIcon },
  { key: 'SoccerBallIcon', Icon: SoccerBallIcon },
  { key: 'VolleyballIcon', Icon: VolleyballIcon },
  { key: 'TennisBallIcon', Icon: TennisBallIcon },
  { key: 'FootballIcon', Icon: FootballIcon },
  { key: 'TrophyIcon', Icon: TrophyIcon },
  { key: 'MedalIcon', Icon: MedalIcon },
  { key: 'MaskHappyIcon', Icon: MaskHappyIcon },
  { key: 'FilmSlateIcon', Icon: FilmSlateIcon },
  { key: 'FilmStripIcon', Icon: FilmStripIcon },
  { key: 'VideoCameraIcon', Icon: VideoCameraIcon },
  { key: 'CameraIcon', Icon: CameraIcon },
  { key: 'ImageIcon', Icon: ImageIcon },
  { key: 'PaletteIcon', Icon: PaletteIcon },
  { key: 'PaintBrushIcon', Icon: PaintBrushIcon },
  { key: 'SparkleIcon', Icon: SparkleIcon },
  { key: 'ConfettiIcon', Icon: ConfettiIcon },
  { key: 'TicketIcon', Icon: TicketIcon },
  { key: 'QrCodeIcon', Icon: QrCodeIcon },
  { key: 'SealCheckIcon', Icon: SealCheckIcon },
  { key: 'StorefrontIcon', Icon: StorefrontIcon },
  { key: 'ShoppingBagIcon', Icon: ShoppingBagIcon },
  { key: 'ForkKnifeIcon', Icon: ForkKnifeIcon },
  { key: 'CoffeeIcon', Icon: CoffeeIcon },
  { key: 'WineIcon', Icon: WineIcon },
  { key: 'CarIcon', Icon: CarIcon },
  { key: 'TrainIcon', Icon: TrainIcon },
  { key: 'AirplaneInFlightIcon', Icon: AirplaneInFlightIcon },
  { key: 'BoatIcon', Icon: BoatIcon },
  { key: 'MapPinIcon', Icon: MapPinIcon },
  { key: 'GlobeIcon', Icon: GlobeIcon },
  { key: 'BuildingsIcon', Icon: BuildingsIcon },
  { key: 'UsersIcon', Icon: UsersIcon },
  { key: 'UsersThreeIcon', Icon: UsersThreeIcon },
  { key: 'HandHeartIcon', Icon: HandHeartIcon },
  { key: 'CalendarBlankIcon', Icon: CalendarBlankIcon },
  { key: 'ClockIcon', Icon: ClockIcon },
  { key: 'SunIcon', Icon: SunIcon },
  { key: 'MoonIcon', Icon: MoonIcon },
  { key: 'TreePalmIcon', Icon: TreePalmIcon },
  { key: 'TreeIcon', Icon: TreeIcon },
  { key: 'FlowerIcon', Icon: FlowerIcon },
  { key: 'MountainsIcon', Icon: MountainsIcon },
  { key: 'WavesIcon', Icon: WavesIcon },
  { key: 'HeartIcon', Icon: HeartIcon },
  { key: 'StarIcon', Icon: StarIcon },
  { key: 'FireIcon', Icon: FireIcon },
  { key: 'LightningIcon', Icon: LightningIcon },
  { key: 'ShieldCheckIcon', Icon: ShieldCheckIcon },
  { key: 'BriefcaseIcon', Icon: BriefcaseIcon },
  { key: 'GraduationCapIcon', Icon: GraduationCapIcon },
  { key: 'BookOpenIcon', Icon: BookOpenIcon },
  { key: 'CodeIcon', Icon: CodeIcon },
  { key: 'CpuIcon', Icon: CpuIcon },
  { key: 'GameControllerIcon', Icon: GameControllerIcon },
  { key: 'DiceFiveIcon', Icon: DiceFiveIcon },
  { key: 'RocketLaunchIcon', Icon: RocketLaunchIcon },
];

export const CATEGORY_PHOSPHOR_ICON_MAP = new Map(
  CATEGORY_PHOSPHOR_ICONS.map((e) => [e.key, e.Icon] as const),
);
